cmake_minimum_required(VERSION 3.5)
project(IT)

file(GLOB_RECURSE sources src/main/*.cpp)
file(GLOB_RECURSE sources_test src/test/*.cpp)
file(GLOB_RECURSE data resources/*)

# -std -save-temps -Wall -Wextra -pedantic